### ISSUE TITLE
Compilation warnings with gcc 13.1.1

### ISSUE THREAD

**Issue by ksbhaskar** [anet-be/lua-yottadb#24] opened 2023-05-10 18:04 UTC
This is on a current EndeavourOS (Arch Linux) system with the current master branch of YottaDB.

```
$ sudo make install
gcc -g -std=c99 -I/usr/local/lib/yottadb/r139_20230509-1 -I/usr/include/lua5.4 -Wno-discarded-qualifiers -shared -fPIC -o _yottadb.so _yottadb.c -L/usr/local/lib/yottadb/r139_20230509-1 -lyottadb 
_yottadb.c: In function ‘lock’:
_yottadb.c:498:75: warning: passing argument 2 of ‘ydb_call_variadic_plist_func’ makes pointer from integer without a cast [-Wint-conversion]
  498 |   int status = ydb_call_variadic_plist_func((ydb_vplist_func)&ydb_lock_s, (uintptr_t)args);
      |                                                                           ^~~~~~~~~~~~~~~
      |                                                                           |
      |                                                                           long unsigned int
In file included from _yottadb.c:7:
/usr/local/lib/yottadb/r139_20230509-1/libyottadb.h:348:75: note: expected ‘gparam_list *’ {aka ‘struct gparam_list_struct *’} but argument is of type ‘long unsigned int’
  348 | int     ydb_call_variadic_plist_func(ydb_vplist_func cgfunc, gparam_list *cvplist); /* Used by API wrappers for other languages to
      |                                                              ~~~~~~~~~~~~~^~~~~~~
install -d /usr/local/share/lua/5.4 /usr/local/lib/lua/5.4
install _yottadb.so /usr/local/lib/lua/5.4
install yottadb.lua /usr/local/share/lua/5.4
$ gcc --version
gcc (GCC) 13.1.1 20230429
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$

**Comment by berwynhoyt** [comment] 2023-05-10 23:38
It seems to be having trouble with _yottadb.c. But there is no _yottadb.c file in the latest v1.x release of lua-yottdb. Are you sure that you're not trying to build the old version 0.1?

**Comment by ksbhaskar** [comment] 2023-05-11 01:49
Thank you.  yes, a newbie type error. I did a `git fetch` forgot a `git merge`! It's much better now:

```
$ make
gcc yottadb.c callins.c compat-5.3/c-api/compat-5.3.c -o _yottadb.so  -shared -Wl,--version-script=exports.map -g -fPIC -std=c11 -I/usr/local/lib/yottadb/r139_20230509-1 -I/usr/include/lua5.4 -pedantic -Wall -Wno-unknown-pragmas -Wno-discarded-qualifiers -L/usr/local/lib/yottadb/r139_20230509-1 -lyottadb -Wl,-rpath,/usr/local/lib/yottadb/r139_20230509-1 -Wl,--gc-sections
$ make test 1>~/tmp/luamaketest_out.txt 2 >~/tmp/luamaketest_err.txt
```

There was one error in the `make test`. Stdout and stderr files attached.
[luamaketest_err.txt](https://github.com/anet-be/lua-yottadb/files/11447381/luamaketest_err.txt)
[luamaketest_out.txt](https://github.com/anet-be/lua-yottadb/files/11447382/luamaketest_out.txt)

**Comment by berwynhoyt** [comment] 2023-05-11 04:20
Unfortunately, I am unable to reproduce this problem. Perhaps `make clean`?

Failing that, perhaps you could help diagnose it yourself by adding the following line 2180 in tests/test.lua so that both lines look like this:
```
  print(out1, out2, _yottadb.message(_yottadb.YDB_ERR_INVSTRLEN))
  assert(not out1 and out2==_yottadb.message(_yottadb.YDB_ERR_INVSTRLEN))
```
out1 should print false and out2 should print the same as YDB error INVSTRLEN

**Comment by berwynhoyt** [comment] 2023-05-11 04:26
On second thought, I suspect that you're using a different version of YDB that handles the case being tested for rather than producing the expected error. Does your version of YDB allocate more space for the return value of IO strings than the string that is supplied. I'm using r1.35.

**Comment by ksbhaskar** [comment] 2023-05-11 22:48
I changed test.lua so that the relevant lines read as follows:

```
  print(out1, out2, _yottadb.message(_yottadb.YDB_ERR_INVSTRLEN))
  assert(not out1 and out2==_yottadb.message(_yottadb.YDB_ERR_INVSTRLEN))
```

`make test` now produces:

```
Running test_callin.
true    abc     YDB Error: -150375522: %YDB-E-INVSTRLEN, Invalid string length !UL: max !UL
Failed!
tests/test.lua:2182: assertion failed!
stack traceback:
        tests/test.lua:2182: in function 'test_callin'
        [C]: in function 'xpcall'
        tests/test.lua:2302: in main chunk
        [C]: in ?
```

**Comment by berwynhoyt** [comment] 2023-05-11 22:56
Then that confirms my diagnosis, thanks.
It appears that YDB has changed since v1.35 so that it no longer give an error if the IO input is too short for the output. Is this a change that you would expect of YDB?

**Comment by berwynhoyt** [comment] 2023-05-13 05:19
You are looking for INVSTRLEN handling in `yottadb.c`, but the call-in handling is in `callins.c`.

I don't think it would be wise to automatically retry a callin when there is a INVSTRLEN error, because that would run arbitrary user code twice. For example, imagine if a callin was called to take $5 out of someone's account and return the remaining balance. If that code were silently called twice (e.g., if the resulting balance didn't fit in the supplied string), then the app would steal from the user.

The issue you linked: [Copy only whatever can be safely copied for ydb_string_t structures](https://gitlab.com/YottaDB/DB/YDB/-/issues/564) sounds to me like it's right in the ballpark of what we're talking about. Except that it doesn't appear to be applied to the version you're testing against. Let's review the situation:

You will see from line 2160 in `tests/test.lua` that the call-in table entry being invoked is as follows:
  `  concat3: ydb_string_t* concat^unittest(I:ydb_char_t*, I:ydb_string_t*, IO:ydb_string_t*, O:ydb_string_t*)`
The Lua invokation looks like this:
  `  out1, out2, out3 = table1.concat3('a','b','c', '')`.
Where `out1` receives the returned value; `out2` and `out3` receive param3 (`IO`) and param4 (`O`) strings. But our test is trying to return `'abc'` in `out2`, which is longer than its input `'b'`.

Now, unless a preallocation is specified in the callin table (it isn't specified in this one), callins.c function cast2ydb() mallocs YDB_MAX_STR for any `IO` or `O` parameter, just to be safe, because it's impossible to tell YDB how much space is allocated in the ydb_string_t struct. (Ideally, it should use ydb_buffer_t, but this isn't available for callins until a later YDB (r1.36?)).

However, even though cast2ydb() allocates YDB_MAX_STR, for IO parameters, YDB_ r1.35 doesn't use it. Instead, YDB assumes the allocated length equals the length of the supplied IO string and returns INVSTRLEN error if it can't fit the result in the length of the supplied IO string. Here is a [note that you wrote](https://gitlab.com/YottaDB/DB/YDB/-/issues/564#note_315682793) to this effect three years ago. So, `tests/test.lua` is testing that YDB actually does this.

Given that, perhaps my cast2ydb() shouldn't actually preallocate YDB_MAX_STR. And once we resolve this, I could change it to that effect. HOWEVER, as you have noticed, the version of YDB that you are testing against does not seem to check the IO string length because you have just seen this test fail. This begs the question: "What version of YDB are you testing against?" and "Is this a regression, or are you testing against a version older than the mixfeature?"

This is a lot of discussion. I hope it makes sense.

**Comment by ksbhaskar** [comment] 2023-05-15 16:11
@berwynhoyt I was barking up the wrong tree by looking at the Simple API rather than call-ins to M. I am testing with r1.39, which is the current master branch. I believe you should use `ydb_buffer_t`, change the tests, and require a minimum release of r1.36.

Notes:

- [YDB#446](https://gitlab.com/YottaDB/DB/YDB/-/issues/446) in r1.26 addressed a misfeature in the design of call-ins that YottaDB inherited from the upstream design (which admittedly was the handiwork of those of us at YottaDB who worked on the upstream software and designed the call-in API).
- As that caused an incompatibility for applications that ran on the upstream code base and on YottaDB, [YDB#564](https://gitlab.com/YottaDB/DB/YDB/-/issues/564) undid the change in r1.36. Also in r1.36 [YDB#565](https://gitlab.com/YottaDB/DB/YDB/-/issues/565) added `ydb_buffer_t` for passing string values.
- YottaDB release numbers end in even digits. So r1.36, r1.38, etc. are released versions of YottaDB. Odd numbered digits indicate code in flight between releases. As r1.35 is the master branch between r1.34 and r1.36, the r1.35 you are looking at, may or may not include YDB#564 and YDB#565. The master branch I am looking at identifies itself as r1.39, because it is post r1.38 (the next release will likely be r2.00).

I hope this helps. Apologies for any confusion.

**Comment by berwynhoyt** [comment] 2023-05-17 03:24
That was most helpful, thank you. I've now fixed this and tested it on r1.38, so you should be good to go. I will mark this issue as closed.

I also took the opportunity to make lua-yottadb auto-select the most efficient of ydb_string_t/ydb_buffer_t (subject to support by the YDB version in use) when it re-writes the call-in table. See examples/arithmetic.ci for details.

Note that the efficiency PR has also been released since then, so the latest master branch is also now up to lua-yottadb v2.0.

**Closed by berwynhoyt** 2023-05-17 03:24 UTC
